version: "3"
services:
  mysql_docker:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql_docker
    ports: 
      - "3307:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '--password=gestaoDeCadastrosMedicos123' ]
      interval: 1m
      timeout: 10s
      retries: 5       
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: romulo
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_ROOT_HOST: "%"
      MYSQL_PORT: 3306
      MYSQL_CHARSET: utf8
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_docker
    depends_on:
      mysql_docker:
        condition: service_healthy
    links: 
      - mysql_docker:db
    ports:
      - 8857:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_PORT: 3307
      MYSQL_DATABASE: api
      MYSQL_CHARSET: utf8
    restart: always